name: whistlestop
favicon: null
layout_spectrum: 0.11439271527342498
typography_spectrum: 0.4752139577176422
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e7ed'
    - '#aab479'
    - '#ea90be'
    - '#e35896'
    - '#e02b75'
  brandStrength: 0.9680284860078245
  lightness: 0.48767049447633326
  saturation: 0.6975049739703536
  rhythmicContrast: 0.9601185065694153
purpose: []
