name: whistlestop
favicon: null
layout_spectrum: 0.25603
typography_spectrum: 0.4752139577176422
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffa337'
    - '#212739'
    - '#e7ffff'
    - '#00a383'
    - '#ff416a'
  brandStrength: 0.9680284860078245
  lightness: 0.48767049447633326
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
